package br.net.rwd.sisescola.enumerado;

public enum Profissao {

	ACUPUNTURISTA("Acupunturista"),
	ADMINISTRADOR_DE_BANCO_DE_DADOS("Administrador de Banco de Dados"),
	ADMINISTRADOR_DE_BASE_DE_DADOS("Administrador de Base de Dados"),
	ADMINISTRADOR_DE_EMPRESAS("Administrador de Empresas"),
	ADMINISTRADOR_DE_REDES("Administrador de Redes"),
	ADMINISTRADOR_DE_SISTEMAS("Administrador de Sistemas"),
	ADMINISTRADOR_HOSPITALAR("Administrador Hospitalar"),
	ADMINISTRADOR_PÚBLICO("Administrador Público"),
	ADVOGADO("Advogado"),
	AEROMOÇA("Aeromoça"),
	AERONAUTA("Aeronauta"),
	AEROVIÁRIO("Aeroviário"),
	AFIADOR_DE_FERRAMENTAS("Afiador de Ferramentas"),
	AGENTE_COMUNITÁRIO_DE_SAÚDE("Agente Comunitário de Saúde"),
	AGENTE_DE_DEFESA_SANITÁRIA("Agente de Defesa Sanitária"),
	AGENTE_DE_VIAGENS("Agente de Viagens"),
	AGENTE_FUNERÁRIO("Agente Funerário"),
	AGENTE_PENITENCIÁRIO("Agente Penitenciário"),
	AGRICULTOR("Agricultor"),
	AGRIMENSOR("Agrimensor"),
	AGRÔNOMO("Agrônomo"),
	AJUDANTE_DE_PRODUÇÃO("Ajudante de Produção"),
	ALERGOLOGISTA("Alergologista"),
	ALFAIATE("Alfaiate"),
	ALMIRANTE("Almirante"),
	ALMOXARIFE("Almoxarife"),
	AMBIENTALISTA("Ambientalista"),
	AMBULANTE("Ambulante"),
	ANALISTA_ADMINISTRADOR_DE_BANCO_DE_DADOS("Analista Administrador de Banco de Dados"),
	ANALISTA_ADMINISTRADOR_DE_REDES("Analista Administrador de Redes"),
	ANALISTA_ADMINISTRATIVO("Analista Administrativo"),
	ANALISTA_ADMINISTRATIVO_CONTROLADORIA("Analista Administrativo Controladoria"),
	ANALISTA_ADMINISTRATIVO_DE_VENDAS("Analista Administrativo de Vendas"),
	ANALISTA_ADMINISTRATIVO_FINANCEIRO("Analista Administrativo Financeiro"),
	ANALISTA_DE_ATENDIMENTO_DE_TELEMARKETING("Analista de Atendimento de Telemarketing"),
	ANALISTA_DE_COMÉRCIO_EXTERIOR("Analista de Comércio Exterior"),
	ANALISTA_DE_COMPRAS("Analista de Compras"),
	ANALISTA_DE_CONTABILIDADE("Analista de Contabilidade"),
	ANALISTA_DE_CRÉDITO("Analista de Crédito"),
	ANALISTA_DE_DEPARTAMENTO_PESSOAL("Analista de Departamento Pessoal"),
	ANALISTA_DE_DESENVOLVIMENTO_WEB("Analista de Desenvolvimento Web"),
	ANALISTA_DE_E_COMMERCE("Analista de e-Commerce"),
	ANALISTA_DE_INFORMÁTICA("Analista de Informática"),
	ANALISTA_DE_INVESTIMENTOS("Analista de Investimentos"),
	ANALISTA_DE_LOGÍSTICA("Analista de Logística"),
	ANALISTA_DE_PROGRAMAÇÃO("Analista de Programação"),
	ANALISTA_DE_RECURSOS_HUMANOS("Analista de Recursos Humanos"),
	ANALISTA_DE_RELAÇÕES_PÚBLICAS("Analista de Relações Públicas"),
	ANALISTA_DE_SEGUROS("Analista de Seguros"),
	ANALISTA_DE_SISTEMAS("Analista de Sistemas"),
	ANALISTA_DE_SUPORTE_TÉCNICO("Analista de Suporte Técnico"),
	ANALISTA_DE_SUPRIMENTOS("Analista de Suprimentos"),
	ANALISTA_FINANCEIRO("Analista Financeiro"),
	ANALISTA_FISCAL("Analista Fiscal"),
	ANALISTA_TECNOLOGIA_DA_INFORMAÇÃO("Analista Tecnologia da Informação"),
	ANESTESIOLOGISTA("Anestesiologista"),
	ANGIOLOGISTA("Angiologista"),
	ANTROPÓLOGO("Antropólogo"),
	APICULTOR("Apicultor"),
	APONTADOR_DE_OBRA("Apontador de Obra"),
	ARGUMENTISTA("Argumentista"),
	ARMADOR("Armador"),
	ARMEIRO("Armeiro"),
	ARQUITETO("Arquiteto"),
	ARQUITETO_DE_INFORMAÇÃO("Arquiteto de Informação"),
	ARQUITETO_URBANISTA("Arquiteto Urbanista"),
	ARQUIVISTA("Arquivista"),
	ARRANJADOR_MUSICAL("Arranjador Musical"),
	ARRUMADEIRA("Arrumadeira"),
	ARTESÃO("Artesão"),
	ARTISTA_PLÁSTICO("Artista Plástico"),
	ARTISTA_TÉCNICO_EM_ESPETÁCULO_DE_DIVERSÕES("Artista Técnico em Espetáculo de Diversões"),
	ASCENSORISTA("Ascensorista"),
	ASSISTENTE_ADMINISTRATIVO("Assistente Administrativo"),
	ASSISTENTE_DE_JORNALISMO("Assistente de Jornalismo"),
	ASSISTENTE_DE_MANUTENÇÃO("Assistente de Manutenção"),
	ASSISTENTE_FINANCEIRO("Assistente Financeiro"),
	ASSISTENTE_SOCIAL("Assistente Social"),
	ATENDENTE("Atendente"),
	ATENDENTE_DE_AGÊNCIA("Atendente de Agência"),
	ATENDENTE_DE_HOTEL("Atendente de Hotel"),
	AUXILIAR_ADMINISTRATIVO("Auxiliar Administrativo"),
	AUXILIAR_ADMINISTRATIVO_DE_VENDAS("Auxiliar Administrativo de Vendas"),
	AUXILIAR_ADMINISTRATIVO_FINANCEIRO("Auxiliar Administrativo Financeiro"),
	AUXILIAR_ADMINISTRATIVO_HOSPITALAR("Auxiliar Administrativo Hospitalar"),
	AUXILIAR_COMERCIAL("Auxiliar Comercial"),
	AUXILIAR_DE_ARQUITETURA("Auxiliar de Arquitetura"),
	AUXILIAR_DE_ATENDIMENTO_DE_TELEMARKETING("Auxiliar de Atendimento de Telemarketing"),
	AUXILIAR_DE_BIBLIOTECA("Auxiliar de Biblioteca"),
	AUXILIAR_DE_COMPRAS("Auxiliar de Compras"),
	AUXILIAR_DE_CONTABILIDADE("Auxiliar de Contabilidade"),
	AUXILIAR_DE_DEPARTAMENTO_PESSOAL("Auxiliar de Departamento Pessoal"),
	AUXILIAR_DE_ESCRITÓRIO("Auxiliar de Escritório"),
	AUXILIAR_DE_LOGÍSTICA("Auxiliar de Logística"),
	AUXILIAR_DE_MARKETING("Auxiliar de Marketing"),
	AUXILIAR_DE_PROGRAMAÇÃO("Auxiliar de Programação"),
	AUXILIAR_DE_PUBLICIDADE_E_PROPAGANDA("Auxiliar de Publicidade e Propaganda"),
	AUXILIAR_DE_RECURSOS_HUMANOS("Auxiliar de Recursos Humanos"),
	AUXILIAR_DE_RELAÇÕES_PÚBLICAS("Auxiliar de Relações Públicas"),
	AUXILIAR_DE_SEGUROS("Auxiliar de Seguros"),
	AUXILIAR_DE_SUPRIMENTOS("Auxiliar de Suprimentos"),
	AUXILIAR_FINANCEIRO_ECONÔMICO("Auxiliar Financeiro Econômico"),
	AUXILIAR_JURÍDICO("Auxiliar Jurídico"),
	BALCONISTA("Balconista"),
	BANCÁRIO("Bancário"),
	BIBLIOTECÁRIO("Bibliotecário"),
	BIBLIOTECONOMISTA("Biblioteconomista"),
	BIÓLOGO("Biólogo"),
	BIOMÉDICO("Biomédico"),
	BIOQUÍMICO("Bioquímico"),
	BORRACHEIRO("Borracheiro"),
	CABELEIREIRO("Cabeleireiro"),
	CADISTA("Cadista"),
	CAIXA("Caixa"),
	CARTEIRO("Carteiro"),
	CATADOR_DE_MATERIAL_RECICLÁVEL("Catador de material reciclável"),
	CENÓGRAFO("Cenógrafo"),
	CERAMISTA("Ceramista"),
	CHAPEIRO("Chapeiro"),
	CHARGISTA("Chargista"),
	CHAVEIRO("Chaveiro"),
	CHEFE_DE_COZINHA("Chefe de Cozinha"),
	CHEFE_DE_RECEPÇÃO("Chefe de Recepção"),
	CHEFE_DE_SISTEMAS("Chefe de sistemas"),
	CIENTISTA("Cientista"),
	CIENTISTA_DA_COMPUTAÇÃO("Cientista da Computação"),
	CIENTISTA_DE_ALIMENTOS("Cientista de Alimentos"),
	CIENTISTA_POLÍTICO("Cientista Político"),
	CINEASTA("Cineasta"),
	CINEGRAFISTA("Cinegrafista"),
	CIRURGIÃO_DENTISTA("Cirurgião Dentista"),
	CLÍNICO_GERAL("Clínico Geral"),
	COLOPROCTOLOGISTA("Coloproctologista"),
	COMISSÁRIO_DE_BORDO("Comissário de Bordo"),
	COMPRADOR("Comprador"),
	COMPRADOR___SUPRIMENTOS("Comprador - Suprimentos"),
	CONSULTOR_DE_E_BUSINESS("Consultor de e-Business"),
	CONSULTOR_DE_TECNOLOGIA_DA_INFORMAÇÃO("Consultor de Tecnologia da Informação"),
	CONTABILISTA("Contabilista"),
	CONTADOR("Contador"),
	CONTROLLER("Controller"),
	COORDENADOR_DE_ENGENHARIA_DE_PROCESSOS("Coordenador de Engenharia de Processos"),
	COORDENADOR_DE_ENGENHARIA_DE_PRODUÇÃO("Coordenador de Engenharia de Produção"),
	COORDENADOR_DE_ENGENHARIA_MECÂNICA("Coordenador de Engenharia Mecânica"),
	COORDENADOR_DE_SISTEMAS("Coordenador de Sistemas"),
	COORDENADOR_DE_TECNOLOGIA_DA_INFORMAÇÃO("Coordenador de Tecnologia da Informação"),
	DEDETIZADOR("Dedetizador"),
	DEGUSTADOR("Degustador"),
	DENTISTA("Dentista"),
	DESENHISTA("Desenhista"),
	DESENHISTA_INDUSTRIAL("Desenhista Industrial"),
	DESENHISTA_TÉCNICO("Desenhista Técnico"),
	DESIGNER_DE_INTERIORES("Designer de Interiores"),
	DESIGNER_DE_MODA("Designer de Moda"),
	DESIGNER_GRÁFICO("Designer Gráfico"),
	DESPACHANTE("Despachante"),
	DETETIVE_PARTICULAR("Detetive Particular"),
	DIAGRAMADOR("Diagramador"),
	DIGITADOR("Digitador"),
	DIPLOMATA("Diplomata"),
	DIRETOR_ADMINISTRATIVO_CONTROLADORIA("Diretor Administrativo Controladoria"),
	DIRETOR_ADMINISTRATIVO_FINANCEIRO("Diretor Administrativo Financeiro"),
	DIRETOR_ADMINISTRATIVO_HOSPITALAR("Diretor Administrativo Hospitalar"),
	DIRETOR_COMERCIAL("Diretor Comercial"),
	DIRETOR_DE_ENGENHARIA_CIVIL("Diretor de Engenharia Civil"),
	DIRETOR_DE_FOTOGRAFIA("Diretor de Fotografia"),
	DIRETOR_DE_INFORMÁTICA("Diretor de Informática"),
	DIRETOR_DE_LOGÍSTICA("Diretor de Logística"),
	DIRETOR_DE_MARKETING("Diretor de Marketing"),
	DIRETOR_DE_MARKETING_ONLINE("Diretor de Marketing Online"),
	DIRETOR_DE_OPERAÇÕES("Diretor de Operações"),
	DIRETOR_DE_RECURSOS_HUMANOS("Diretor de Recursos Humanos"),
	DIRETOR_DE_SISTEMAS("Diretor de Sistemas"),
	DIRETOR_DE_TECNOLOGIA_DA_INFORMAÇÃO("Diretor de Tecnologia da Informação"),
	DIRETOR_ENSINO_FUNDAMENTAL_E_MÉDIO("Diretor Ensino Fundamental e Médio"),
	DIRETOR_ENSINO_SUPERIOR("Diretor Ensino Superior"),
	DIRETOR_INDUSTRIAL("Diretor Industrial"),
	DIRETOR_MÉDICO_HOSPITALAR("Diretor Médico Hospitalar"),
	ECÓLOGO("Ecólogo"),
	ECONOMISTA("Economista"),
	ECONOMISTA_DOMÉSTICO("Economista Doméstico"),
	EDITOR("Editor"),
	EDITOR_DE_CONTEÚDO("Editor de Conteúdo"),
	EDUCADOR("Educador"),
	EDUCADOR_FÍSICO("Educador Físico"),
	ELETRICISTA("Eletricista"),
	ELETRICISTA_DE_AUTOMÓVEIS("Eletricista de Automóveis"),
	EMBALADOR("Embalador"),
	EMBALSAMADOR("Embalsamador"),
	ENCANADOR("Encanador"),
	ENCARREGADO("Encarregado"),
	ENDOCRINOLOGISTA("Endocrinologista"),
	ENDODONTISTAS("Endodontistas"),
	ENFERMEIRA("Enfermeira"),
	ENFERMEIRO("Enfermeiro"),
	ENFERMEIRO_DO_TRABALHO("Enfermeiro do Trabalho"),
	ENGENHARIA_DE_HORTICULTURA("Engenharia de Horticultura"),
	ENGENHEIRO_ACÚSTICO("Engenheiro Acústico"),
	ENGENHEIRO_AERONÁUTICO("Engenheiro Aeronáutico"),
	ENGENHEIRO_AGRÍCOLA("Engenheiro Agrícola"),
	ENGENHEIRO_AGRIMENSOR("Engenheiro Agrimensor"),
	ENGENHEIRO_AGRÔNOMO("Engenheiro Agrônomo"),
	ENGENHEIRO_AMBIENTAL("Engenheiro Ambiental"),
	ENGENHEIRO_BIOQUÍMICO("Engenheiro Bioquímico"),
	ENGENHEIRO_CARTOGRÁFICO("Engenheiro Cartográfico"),
	ENGENHEIRO_CIVIL("Engenheiro Civil"),
	ENGENHEIRO_DA_COMPUTAÇÃO("Engenheiro da Computação"),
	ENGENHEIRO_DE_ALIMENTOS("Engenheiro de Alimentos"),
	ENGENHEIRO_DE_CONTROLE_E_AUTOMAÇÃO("Engenheiro de Controle e Automação"),
	ENGENHEIRO_DE_ENERGIA("Engenheiro de Energia"),
	ENGENHEIRO_DE_LOGÍSTICA("Engenheiro de Logística"),
	ENGENHEIRO_DE_MANUFATURA("Engenheiro de Manufatura"),
	ENGENHEIRO_DE_MATERIAIS("Engenheiro de Materiais"),
	ENGENHEIRO_DE_MEIO_AMBIENTE("Engenheiro de Meio Ambiente"),
	ENGENHEIRO_DE_MINAS("Engenheiro de Minas"),
	ENGENHEIRO_DE_PETRÓLEO("Engenheiro de Petróleo"),
	ENGENHEIRO_DE_PROCESSOS("Engenheiro de Processos"),
	ENGENHEIRO_DE_PRODUÇÃO("Engenheiro de Produção"),
	ENGENHEIRO_DE_PRODUÇÃO_AGROINDUSTRIAL("Engenheiro de Produção Agroindustrial"),
	ENGENHEIRO_DE_PROJETOS("Engenheiro de Projetos"),
	ENGENHEIRO_DE_SEGURANÇA_DO_TRABALHO("Engenheiro de Segurança do Trabalho"),
	ENGENHEIRO_DE_SOM("Engenheiro de Som"),
	ENGENHEIRO_DE_TELECOMUNICAÇÕES("Engenheiro de Telecomunicações"),
	ENGENHEIRO_DE_TRANSPORTES("Engenheiro de Transportes"),
	ENGENHEIRO_ELETRICISTA("Engenheiro Eletricista"),
	ENGENHEIRO_FÍSICO("Engenheiro Físico"),
	ENGENHEIRO_FLORESTAL("Engenheiro Florestal"),
	ENGENHEIRO_INDUSTRIAL("Engenheiro Industrial"),
	ENGENHEIRO_MECÂNICO("Engenheiro Mecânico"),
	ENGENHEIRO_MECATRÔNICO("Engenheiro Mecatrônico"),
	ENGENHEIRO_METALÚRGICO("Engenheiro Metalúrgico"),
	ENGENHEIRO_NAVAL("Engenheiro Naval"),
	ENGENHEIRO_ORÇAMENTISTA("Engenheiro Orçamentista"),
	ENGENHEIRO_QUÍMICO("Engenheiro Químico"),
	ENGENHEIRO_TÊXTIL("Engenheiro Têxtil"),
	ENTOMOLOGISTA_FORENSE_("Entomologista forense "),
	ESPECIALISTA_EM_ANÁLISE_DA_WEB("Especialista em análise da web"),
	ESPECIALISTA_EM_AUSÊNCIA_DE_GRAVIDADE("Especialista em ausência de gravidade "),
	ESPECIALISTA_EM_LIXO("Especialista em lixo"),
	ESPECIALISTA_EM_SEM("Especialista em SEM (Search Engine Marketing)"),
	ESPECIALISTA_EM_SEO("Especialista em SEO (Search Engine Optimization)"),
	ESPECIALISTA_EM_USABILIDADE("Especialista em usabilidade"),
	ESTAGIÁRIO("Estagiário"),
	ESTAGIÁRIO_ADMINISTRATIVO_DE_VENDAS("Estagiário Administrativo de Vendas"),
	ESTAGIÁRIO_ADMINISTRATIVO_EM_CONTROLADORIA("Estagiário Administrativo em Controladoria"),
	ESTAGIÁRIO_ADMINISTRATIVO_FINANCEIRO("Estagiário Administrativo Financeiro"),
	ESTAGIÁRIO_DE_COMPRAS("Estagiário de Compras"),
	ESTAGIÁRIO_DE_E_COMMERCE("Estagiário de e-Commerce"),
	ESTAGIÁRIO_DE_ENGENHARIA_DE_PROCESSOS("Estagiário de Engenharia de Processos"),
	ESTAGIÁRIO_DE_ENGENHARIA_DE_PRODUÇÃO("Estagiário de Engenharia de Produção"),
	ESTAGIÁRIO_DE_ENGENHARIA_DO_MEIO_AMBIENTE("Estagiário de Engenharia do Meio Ambiente"),
	ESTAGIÁRIO_DE_ENGENHARIA_MECÂNICA("Estagiário de Engenharia Mecânica"),
	ESTAGIÁRIO_DE_ENGENHARIA_MECATRÔNICA("Estagiário de Engenharia Mecatrônica"),
	ESTAGIÁRIO_DE_INFORMÁTICA("Estagiário de Informática"),
	ESTAGIÁRIO_DE_JORNALISMO("Estagiário de Jornalismo"),
	ESTAGIÁRIO_DE_LOGÍSTICA("Estagiário de Logística"),
	ESTAGIÁRIO_DE_MARKETING("Estagiário de Marketing"),
	ESTAGIÁRIO_DE_PROGRAMAÇÃO("Estagiário de Programação"),
	ESTAGIÁRIO_DE_RELAÇÕES_PÚBLICAS("Estagiário de Relações Públicas"),
	ESTAGIÁRIO_DE_SISTEMAS("Estagiário de Sistemas"),
	ESTAGIÁRIO_DE_SUPORTE_TÉCNICO("Estagiário de Suporte Técnico"),
	ESTAGIÁRIO_DE_SUPRIMENTOS("Estagiário de Suprimentos"),
	ESTAGIÁRIO_DE_TURISMO("Estagiário de Turismo"),
	ESTAGIÁRIO_DE_VENDAS("Estagiário de Vendas"),
	ESTAGIÁRIO_DE_ZOOTECNIA("Estagiário de Zootecnia"),
	ESTAGIÁRIO_EM_ADMINISTRAÇÃO_HOSPITALAR("Estagiário em Administração Hospitalar"),
	ESTAGIÁRIO_EM_ADMINISTRAÇÃO_PÚBLICA("Estagiário em Administração Pública"),
	ESTAGIÁRIO_EM_CONTABILIDADE("Estagiário em Contabilidade"),
	ESTAGIÁRIO_EM_DIREITO("Estagiário em Direito"),
	ESTAGIÁRIO_EM_ENGENHARIA_AGRÍCOLA("Estagiário em Engenharia Agrícola"),
	ESTAGIÁRIO_EM_ENGENHARIA_AGRÔNOMA("Estagiário em Engenharia Agrônoma"),
	ESTAGIÁRIO_EM_ENGENHARIA_CIVIL("Estagiário em Engenharia Civil"),
	ESTAGIÁRIO_EM_ENGENHARIA_DE_AGRIMENSURA("Estagiário em Engenharia de Agrimensura"),
	ESTAGIÁRIO_EM_ENGENHARIA_ELÉTRICA("Estagiário em Engenharia Elétrica"),
	ESTAGIÁRIO_EM_ENGENHARIA_QUÍMICA("Estagiário em Engenharia Química"),
	ESTAGIÁRIO_EM_SERVIÇO_SOCIAL("Estagiário em Serviço Social"),
	ESTAGIÁRIO_FINANCEIRO("Estagiário Financeiro"),
	ESTAGIÁRIO_WEB("Estagiário Web"),
	ESTÁGIO_EM_RECURSOS_HUMANOS("Estágio em Recursos Humanos"),
	ESTÁGIO_EM_WEB_DEVELOPMENT("Estágio em Web Development"),
	ESTATÍSTICO("Estatístico"),
	ESTERILIZADOR_DE_ELEFANTES("Esterilizador de elefantes"),
	ESTETICISTA("Esteticista"),
	ESTILISTA("Estilista"),
	EXAMINADOR_ANTIDOPING("Examinador antidoping"),
	FARMACÊUTICO("Farmacêutico"),
	FATURISTA("Faturista"),
	FERRAMENTEIRO("Ferramenteiro"),
	FISCAL_DE_LOJA("Fiscal de Loja"),
	FÍSICO("Físico"),
	FISIOTERAPEUTA("Fisioterapeuta"),
	FLORISTA("Florista"),
	FONOAUDIÓLOGO("Fonoaudiólogo"),
	FORNEIRO("Forneiro"),
	FOTÓGRAFO("Fotógrafo"),
	FRENTISTA("Frentista"),
	FRESADOR("Fresador"),
	FUNDIDOR("Fundidor"),
	FUNILEIRO("Funileiro"),
	GARÇOM("Garçom"),
	GARÍ("Garí"),
	GASTROENTEROLOGISTA("Gastroenterologista"),
	GASTRÔNOMO("Gastrônomo"),
	GEOFÍSICO("Geofísico"),
	GEÓGRAFO("Geógrafo"),
	GEÓLOGO("Geólogo"),
	GERENTE("Gerente"),
	GERENTE_ADMINISTRADOR_DE_REDE("Gerente Administrador de Rede"),
	GERENTE_ADMINISTRATIVO_CONTROLADORIA("Gerente Administrativo Controladoria"),
	GERENTE_ADMINISTRATIVO_DE_VENDAS("Gerente Administrativo de Vendas"),
	GERENTE_ADMINISTRATIVO_FINANCEIRO("Gerente Administrativo Financeiro"),
	GERENTE_ADMINISTRATIVO_HOSPITALAR("Gerente Administrativo Hospitalar"),
	GERENTE_COMERCIAL("Gerente Comercial"),
	GERENTE_COMÉRCIO_VAREJISTA("Gerente Comércio Varejista"),
	GERENTE_DA_QUALIDADE("Gerente da Qualidade"),
	GERENTE_DE_AGÊNCIA("Gerente de Agência"),
	GERENTE_DE_ATENDIMENTO_DE_TELEMARKETING("Gerente de Atendimento de Telemarketing"),
	GERENTE_DE_BANCO("Gerente de Banco"),
	GERENTE_DE_COMPRAS("Gerente de Compras"),
	GERENTE_DE_COMUNIDADES_E_REDES_SOCIAIS("Gerente de Comunidades e Redes Sociais"),
	GERENTE_DE_CONTABILIDADE("Gerente de Contabilidade"),
	GERENTE_DE_CORPORATE_FINANCE("Gerente de Corporate Finance"),
	GERENTE_DE_CRÉDITO("Gerente de Crédito"),
	GERENTE_DE_DEPARTAMENTO_PESSOAL("Gerente de Departamento Pessoal"),
	GERENTE_DE_E_COMMERCE("Gerente de E-commerce"),
	GERENTE_DE_ENGENHARIA_CIVIL("Gerente de Engenharia civil"),
	GERENTE_DE_ENGENHARIA_DE_COMPUTAÇÃO("Gerente de Engenharia de Computação"),
	GERENTE_DE_ENGENHARIA_DE_MEIO_AMBIENTE("Gerente de Engenharia de Meio Ambiente"),
	GERENTE_DE_ENGENHARIA_DE_PROCESSOS("Gerente de Engenharia de Processos"),
	GERENTE_DE_ENGENHARIA_DE_PRODUÇÃO("Gerente de Engenharia de Produção"),
	GERENTE_DE_ENGENHARIA_DE_PROJETOS("Gerente de Engenharia de Projetos"),
	GERENTE_DE_ENGENHARIA_ELÉTRICA("Gerente de Engenharia Elétrica"),
	GERENTE_DE_ENGENHARIA_MECÂNICA("Gerente de Engenharia Mecânica"),
	GERENTE_DE_FARMÁCIA("Gerente de Farmácia"),
	GERENTE_DE_HOSPEDAGEM("Gerente de Hospedagem"),
	GERENTE_DE_HOTEL("Gerente de Hotel"),
	GERENTE_DE_INFORMÁTICA("Gerente de Informática"),
	GERENTE_DE_INVESTIMENTOS("Gerente de Investimentos"),
	GERENTE_DE_JORNALISMO("Gerente de Jornalismo"),
	GERENTE_DE_LOGÍSTICA("Gerente de Logística"),
	GERENTE_DE_MANUTENÇÃO("Gerente de Manutenção"),
	GERENTE_DE_MARKETING("Gerente de Marketing"),
	GERENTE_DE_MERCADO_FINANCEIRO("Gerente de Mercado Financeiro"),
	GERENTE_DE_MODA("Gerente de Moda"),
	GERENTE_DE_OPERAÇÕES("Gerente de Operações"),
	GERENTE_DE_PRODUTOS("Gerente de Produtos"),
	GERENTE_DE_PROGRAMAÇÃO("Gerente de Programação"),
	GERENTE_DE_PROJETOS("Gerente de Projetos"),
	GERENTE_DE_PUBLICIDADE_E_PROPAGANDA("Gerente de Publicidade e Propaganda"),
	GERENTE_DE_RECURSOS_HUMANOS("Gerente de Recursos Humanos"),
	GERENTE_DE_RELAÇÕES_PÚBLICAS("Gerente de Relações Públicas"),
	GERENTE_DE_RESTAURANTES("Gerente de Restaurantes"),
	GERENTE_DE_SEGUROS("Gerente de Seguros"),
	GERENTE_DE_SISTEMAS("Gerente de Sistemas"),
	GERENTE_DE_SUPORTE_TÉCNICO("Gerente de Suporte Técnico"),
	GERENTE_DE_SUPRIMENTOS("Gerente de Suprimentos"),
	GERENTE_DE_TECNOLOGIA_DA_INFORMAÇÃO("Gerente de Tecnologia da Informação"),
	GERENTE_DE_TURISMO("Gerente de Turismo"),
	GERENTE_DE_VENDAS("Gerente de Vendas"),
	GERENTE_FINANCEIRO_ECONOMICO("Gerente Financeiro Economico"),
	GERENTE_INDUSTRIAL("Gerente Industrial"),
	GERENTE_JURÍDICO("Gerente Jurídico"),
	GERIATRA("Geriatra"),
	GESTOR_AMBIENTAL("Gestor Ambiental"),
	GESTOR_DE_QUALIDADE("Gestor de Qualidade"),
	GESTOR_DE_RECURSOS_HUMANOS("Gestor de Recursos Humanos"),
	GESTOR_DE_TECNOLOGIA_DA_INFORMAÇÃO("Gestor de Tecnologia da Informação"),
	GESTOR_PÚBLICO("Gestor Público"),
	GINECOLOGISTA("Ginecologista"),
	GOVERNANTA("Governanta"),
	GUIA_TURÍSTICO("Guia Turístico"),
	GUINCHEIRO("Guincheiro"),
	HEADHUNTER("Headhunter"),
	HEMATOLOGISTA("Hematologista"),
	HISTORIADOR("Historiador"),
	HOMEOPATA("Homeopata"),
	HOSTESS("Hostess"),
	ILUSTRADOR("Ilustrador"),
	IMPLANTODONTISTA("Implantodontista"),
	IMPORTADOR("Importador"),
	IMPRESSOR("Impressor"),
	IMUNOLOGISTA("Imunologista"),
	INFECTOLOGISTA("Infectologista"),
	INSPETOR_DA_QUALIDADE("Inspetor da qualidade"),
	INSTRUMENTADOR_CIRÚRGICO("Instrumentador Cirúrgico"),
	INSTRUMENTISTA_DE_LABORATÓRIO("Instrumentista de Laboratório"),
	INSTRUMENTISTA_MUSICAL("Instrumentista Musical"),
	INSTRUTOR_DE_INFORMÁTICA("Instrutor de Informática"),
	INTÉRPRETE("Intérprete"),
	INVESTIGADOR_DE_POLÍCIA("Investigador de Polícia"),
	INVESTIGADOR_PARTICULAR("Investigador Particular"),
	JARDINEIRO("Jardineiro"),
	JORNALEIRO("Jornaleiro"),
	JORNALISTA("Jornalista"),
	JUIZ_AUDITOR("Juiz Auditor"),
	JUIZ_DE_DIREITO("Juiz de Direito"),
	JUIZ_DE_FUTEBOL("Juiz de futebol"),
	LABORATORISTA("Laboratorista"),
	LAMINADOR("Laminador"),
	LEILOEIRO("Leiloeiro"),
	LETRISTA("Letrista"),
	LÍDER_DE_FERRAMENTARIA("Líder de Ferramentaria"),
	LÍDER_DE_PRODUÇÃO("Líder de Produção"),
	LOCUTOR("Locutor"),
	LUBRIFICADOR("Lubrificador"),
	LUSTRADOR("Lustrador"),
	LUTHIER("Luthier"),
	MAITRE("Maitre"),
	MANICURE("Manicure"),
	MANOBRISTA("Manobrista"),
	MAQUIADOR("Maquiador"),
	MARCENEIRO("Marceneiro"),
	MARINHEIRO("Marinheiro"),
	MASSAGISTA("Massagista"),
	MASSOTERAPEUTA("Massoterapeuta"),
	MATEMÁTICO("Matemático"),
	MECÂNICO("Mecânico"),
	MECÂNICO_DE_VÔO("Mecânico de vôo"),
	MECANÓGRAFO("Mecanógrafo"),
	MÉDICO("Médico"),
	MÉDICO_CIRURGIÃO("Médico Cirurgião"),
	MÉDICO_GENETICISTA("Médico Geneticista"),
	MÉDICO_LEGISTA("Médico Legista"),
	MÉDICO_NUCLEAR("Médico Nuclear"),
	MÉDICO_VETERINÁRIO("Médico Veterinário"),
	MERGULHADOR("Mergulhador"),
	MERGULHADOR_DE_RISCO("Mergulhador de risco"),
	METALÚRGICO("Metalúrgico"),
	METEOROLOGIA("Meteorologia"),
	MODELISTA("Modelista"),
	MOLDADOR_DE_VIDRO("Moldador de vidro"),
	MOTOBOY("Motoboy"),
	MOTORISTA("Motorista"),
	MOTOTAXISTA("Mototaxista"),
	MUSEÓLOGO("Museólogo"),
	NEONATOLOGISTA("Neonatologista"),
	NUTRICIONISTA("Nutricionista"),
	OCEANÓGRAFO("Oceanógrafo"),
	OFFICE_BOY("Office boy"),
	OLHEIRO("Olheiro"),
	OPERADOR_DE_BOMBAS("Operador de Bombas"),
	OPERADOR_DE_CAIXA("Operador de Caixa"),
	OPERADOR_DE_CÂMERA("Operador de Câmera"),
	OPERADOR_DE_MÁQUINAS("Operador de Máquinas"),
	OPERADOR_DE_TELEMARKETING_ATIVO("Operador de Telemarketing Ativo"),
	OPERADOR_DE_TELEMARKETING_RECEPTIVO("Operador de Telemarketing Receptivo"),
	OPERADOR_DE_TORNO_CNC("Operador de Torno CNC"),
	OPERADOR_DE_TORNO_MECÂNICO("Operador de Torno Mecânico"),
	ORIENTADOR_EDUCACIONAL("Orientador Educacional"),
	ORTESISTA("Ortesista"),
	ORTOPTISTA("Ortoptista"),
	PAISAGISTA("Paisagista"),
	PAPILOSCOPISTA("Papiloscopista"),
	PEDAGOGO("Pedagogo"),
	PEDICURE("Pedicure"),
	PEIXEIRO("Peixeiro"),
	PERFUMISTA("Perfumista"),
	PERITO_JUDICIAL_CONTÁBIL("Perito Judicial Contábil"),
	PESQUISADOR_DE_ENGENHARIA_CIVIL("Pesquisador de Engenharia Civil"),
	PESQUISADOR_DE_FEZES_DE_BALEIA("Pesquisador de fezes de baleia"),
	PODÓLOGO("Podólogo"),
	POLIDOR_DE_FERRAMENTAS("Polidor de Ferramentas"),
	PORTEIRO("Porteiro"),
	PORTUÁRIO("Portuário"),
	PRENSISTA("Prensista"),
	PREPARADOR_DE_MÁQUINAS("Preparador de Máquinas"),
	PROFESSOR("Professor"),
	PROFESSOR_DE_ENSINO_MÉDIO("Professor de Ensino Médio"),
	PROFESSOR_DE_IDIOMAS("Professor de Idiomas"),
	PROFESSOR_ENSINO_FUNDAMENTAL("Professor Ensino Fundamental"),
	PROFESSOR_ENSINO_SUPERIOR("Professor Ensino Superior"),
	PROGRAMADOR("Programador"),
	PROJETISTA("Projetista"),
	PROMOTOR_DE_VENDAS("Promotor de Vendas"),
	PSICÓLOGO("Psicólogo"),
	PUBLICITÁRIO("Publicitário"),
	REBARBADOR_DE_METAL("Rebarbador de Metal"),
	RECEPCIONISTA("Recepcionista"),
	RECREADOR("Recreador"),
	REDATOR("Redator"),
	RELAÇÕES_PÚBLICAS("Relações Públicas"),
	REPÓRTER("Repórter"),
	REPOSITOR_DE_MERCADORIAS("Repositor de Mercadorias"),
	REPRESENTANTE_COMERCIAL("Representante Comercial"),
	RESPONSÁVEL_POR_E_COMMERCE("Responsável por e-Commerce"),
	RETIFICADOR("Retificador"),
	REVISOR("Revisor"),
	SECRETÁRIA("Secretária"),
	SEGURANÇA("Segurança"),
	SEPARADOR("Separador"),
	SERRALHEIRO("Serralheiro"),
	SERVENTE_DE_OBRAS("Servente de Obras"),
	SERVENTUÁRIO("Serventuário"),
	SERVIDOR_PÚBLICO("Servidor Público"),
	SERVIDOR_PÚBLICO_ESTADUAL("Servidor Público Estadual"),
	SERVIDOR_PÚBLICO_FEDERAL("Servidor Público Federal"),
	SERVIDOR_PÚBLICO_MUNICIPAL("Servidor Público Municipal"),
	SEXÓLOGO("Sexólogo"),
	SOCIÓLOGO("Sociólogo"),
	SOLDADOR("Soldador"),
	SONOPLASTA("Sonoplasta"),
	SUPERVISOR_ADMINISTRATIVO_CONTROLADORIA("Supervisor Administrativo Controladoria"),
	SUPERVISOR_ADMINISTRATIVO_DE_VENDAS("Supervisor Administrativo de Vendas"),
	SUPERVISOR_ADMINISTRATIVO_FINANCEIRO("Supervisor Administrativo Financeiro"),
	SUPERVISOR_ADMINISTRATIVO_HOSPITALAR("Supervisor Administrativo Hospitalar"),
	SUPERVISOR_COMERCIAL("Supervisor Comercial"),
	SUPERVISOR_COMÉRCIO_VAREJISTA("Supervisor Comércio Varejista"),
	SUPERVISOR_DE_ATENDIMENTO_DE_TELEMARKETING("Supervisor de Atendimento de Telemarketing"),
	SUPERVISOR_DE_COMPRAS("Supervisor de Compras"),
	SUPERVISOR_DE_CONTABILIDADE("Supervisor de Contabilidade"),
	SUPERVISOR_DE_DEPARTAMENTO_PESSOAL("Supervisor de Departamento Pessoal"),
	SUPERVISOR_DE_E_COMMERCE("Supervisor de e-Commerce"),
	SUPERVISOR_DE_ENGENHARIA_AGRÔNOMA("Supervisor de Engenharia Agrônoma"),
	SUPERVISOR_DE_ENGENHARIA_DA_COMPUTAÇÃO("Supervisor de Engenharia da Computação"),
	SUPERVISOR_DE_ENGENHARIA_DE_MEIO_AMBIENTE("Supervisor de Engenharia de Meio Ambiente"),
	SUPERVISOR_DE_ENGENHARIA_ELÉTRICA("Supervisor de Engenharia Elétrica"),
	SUPERVISOR_DE_ENGENHARIA_QUÍMICA("Supervisor de Engenharia Química"),
	SUPERVISOR_DE_INFORMÁTICA("Supervisor de Informática"),
	SUPERVISOR_DE_JORNALISMO("Supervisor de Jornalismo"),
	SUPERVISOR_DE_LOGÍSTICA("Supervisor de Logística"),
	SUPERVISOR_DE_MANUTENÇÃO("Supervisor de Manutenção"),
	SUPERVISOR_DE_MARKETING("Supervisor de Marketing"),
	SUPERVISOR_DE_OPERAÇÕES("Supervisor de Operações"),
	SUPERVISOR_DE_QUALIDADE("Supervisor de Qualidade"),
	SUPERVISOR_DE_RECURSOS_HUMANOS("Supervisor de Recursos Humanos"),
	SUPERVISOR_DE_RELAÇÕES_PÚBLICAS("Supervisor de Relações Públicas"),
	SUPERVISOR_DE_SEGURANÇA_DO_TRABALHO("Supervisor de Segurança do Trabalho"),
	SUPERVISOR_DE_SEGURANÇA_PATRIMONIAL("Supervisor de Segurança Patrimonial"),
	SUPERVISOR_DE_SEGUROS("Supervisor de Seguros"),
	SUPERVISOR_DE_SUPRIMENTOS("Supervisor de Suprimentos"),
	SUPERVISOR_DE_VENDAS("Supervisor de Vendas"),
	SUPERVISOR_DE_WEB_DEVELOPMENT("Supervisor de Web Development"),
	SUPERVISOR_FINANCEIRO("Supervisor Financeiro"),
	SUPERVISOR_INDUSTRIAL("Supervisor Industrial"),
	TAXIDERMISTA("Taxidermista"),
	TAXISTA("Taxista"),
	TÉCNICO_DE_GESSO("Técnico de Gesso"),
	TÉCNICO_DE_SEGUROS("Técnico de Seguros"),
	TÉCNICO_DE_SOM("Técnico de Som"),
	TÉCNICO_DE_SUPORTE("Técnico de Suporte"),
	TÉCNICO_DE_ZOOTECNIA("Técnico de Zootecnia"),
	TÉCNICO_ELETRICISTA("Técnico Eletricista"),
	TÉCNICO_EM_ADMINISTRAÇÃO_DE_BANCO_DE_DADOS("Técnico em Administração de Banco de Dados"),
	TÉCNICO_EM_ADMINISTRAÇÃO_DE_REDES("Técnico em Administração de Redes"),
	TÉCNICO_EM_AGROPECUÁRIA("Técnico em Agropecuária"),
	TÉCNICO_EM_AUTOMAÇÃO_INDUSTRIAL("Técnico em Automação Industrial"),
	TÉCNICO_EM_DESPORTO("Técnico em Desporto"),
	TÉCNICO_EM_DOCUMENTAÇÃO("Técnico em Documentação"),
	TÉCNICO_EM_EDIFICAÇÕES("Técnico em Edificações"),
	TÉCNICO_EM_ELETRÔNICA("Técnico em Eletrônica"),
	TÉCNICO_EM_ENFERMAGEM("Técnico em Enfermagem"),
	TÉCNICO_EM_FARMÁCIA("Técnico em Farmácia"),
	TÉCNICO_EM_HARDWARE("Técnico em Hardware"),
	TÉCNICO_EM_INFORMÁTICA("Técnico em Informática"),
	TÉCNICO_EM_MANUTENÇÃO("Técnico em Manutenção"),
	TÉCNICO_EM_PROGRAMAÇÃO("Técnico em Programação"),
	TÉCNICO_EM_RADIOLOGIA("Técnico em Radiologia"),
	TÉCNICO_EM_SEGURANÇA_DO_TRABALHO("Técnico em Segurança do Trabalho"),
	TÉCNICO_EM_SISTEMAS("Técnico em Sistemas"),
	TÉCNICO_EM_TAQUIGRAFIA("Técnico em Taquigrafia"),
	TÉCNICO_EM_TECNOLOGIA_DA_INFORMAÇÃO("Técnico em Tecnologia da Informação"),
	TÉCNICO_EM_TELECOMUNICAÇÕES("Técnico em Telecomunicações"),
	TÉCNICO_EM_TRANSPORTES_AÉREOS("Técnico em Transportes Aéreos"),
	TÉCNICO_EM_TRATAMENTO_DE_ÁGUA("Técnico em Tratamento de Água"),
	TÉCNICO_INDUSTRIAL("Técnico Industrial"),
	TÉCNICO_TRIBUTARISTA("Técnico Tributarista"),
	TECNÓLOGO_EM_IRRIGAÇÃO_E_DRENAGEM("Tecnólogo em Irrigação e Drenagem"),
	TECNÓLOGO_EM_SILVICULTURA("Tecnólogo em Silvicultura"),
	TELEFONISTA("Telefonista"),
	TELEGRAFISTA("Telegrafista"),
	TERAPEUTA_OCUPACIONAL("Terapeuta Ocupacional"),
	TESOUREIRO("Tesoureiro"),
	TOPÓGRAFO("Topógrafo"),
	TRADUTOR("Tradutor"),
	TRAFFICKER_WEB("Trafficker Web"),
	TREINADOR("Treinador"),
	TREINADOR_DE_EDUCAÇÃO_FÍSICA("Treinador de Educação Física"),
	ULTRA_SONOGRAFISTA("Ultra-sonografista"),
	URBANISTA("Urbanista"),
	UROLOGISTA("Urologista"),
	VENDEDOR("Vendedor"),
	VENDEDOR_BALCONISTA("Vendedor Balconista"),
	VENDEDOR_EXTERNO("Vendedor Externo"),
	VENDEDOR_INTERNO("Vendedor Interno"),
	VIGILANTE("Vigilante"),
	VISTORIADOR_DE_SINISTROS("Vistoriador de Sinistros"),
	WEB_DESIGNER("Web designer"),
	WEBMASTER("Webmaster"),
	XILÓGRAFO("Xilógrafo"),
	ZELADOR("Zelador"),
	ZOOTECNISTA("Zootecnista");

	private final String profissao;

	Profissao(String profissao) {
	this.profissao = profissao;
	}

	public String getProfissao() {
	return profissao;
	}

	@Override
	public String toString() {
	return profissao.toUpperCase();
	}
	
}
